version: '3.8'

services:
  web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: devcertpass
      ASPNETCORE_Kestrel__Certificates__Default__Path: /devcert.pfx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.0"

    networks:
      - default

    volumes:
      - ../..:/workspaces:cached
      - data-protection-keys:/home/vscode/.aspnet/DataProtection-Keys

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  # https://github.com/citusdata/docker/blob/master/docker-compose.yml
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus"
    restart: unless-stopped
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    networks:
      - default
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager"
    restart: unless-stopped
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    networks:
      - default
    environment: *AUTH
  worker:
    image: "citusdata/citus"
    restart: unless-stopped
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    networks:
      - default
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
 
volumes:
    data-protection-keys:
    healthcheck-volume:

networks:
  default:
